"""add_backtest_tables

Revision ID: 99150d1306d6
Revises: ccc148a75104
Create Date: 2026-05-21 15:06:02.756306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99150d1306d6'
down_revision: Union[str, None] = 'ccc148a75104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy_config', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('max_hold_days', sa.Integer(), nullable=False),
    sa.Column('max_positions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('annual_return', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('profit_trades', sa.Integer(), nullable=False),
    sa.Column('equity_curve', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=20), nullable=False),
    sa.Column('buy_date', sa.Date(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('sell_date', sa.Date(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('sell_reason', sa.String(length=20), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('hold_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_trades')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
