"""add stock data_task screening strategy models

Revision ID: ccc148a75104
Revises: 
Create Date: 2026-05-21 11:10:47.968133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccc148a75104'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('screen_date', sa.Date(), nullable=False),
    sa.Column('stock_code', sa.String(length=10), nullable=False),
    sa.Column('stock_name', sa.String(length=20), nullable=False),
    sa.Column('layer_passed', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_results_screen_date'), 'screening_results', ['screen_date'], unique=False)
    op.create_index(op.f('ix_screening_results_stock_code'), 'screening_results', ['stock_code'], unique=False)
    op.create_table('stocks',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('market', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=50), nullable=True),
    sa.Column('is_st', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('strategy_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategy_configs')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_screening_results_stock_code'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_screen_date'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_table('data_tasks')
    # ### end Alembic commands ###
